// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuh7ZWAHOo9quA045hxHz1uG0Zg8S4UVI',
    appId: '1:299785692288:web:1695c1de9c6732682e3265',
    messagingSenderId: '299785692288',
    projectId: 'chat-app-flutter-fe02d',
    authDomain: 'chat-app-flutter-fe02d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-fe02d.appspot.com',
    measurementId: 'G-F8WNNMDTWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYiRRoKAxlQ3mfQXz8mzEid2K8_6ARI9Y',
    appId: '1:299785692288:android:b4fd4939b0a24e232e3265',
    messagingSenderId: '299785692288',
    projectId: 'chat-app-flutter-fe02d',
    storageBucket: 'chat-app-flutter-fe02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6zyPTrBLivEtrZkpwxeCgW_FlsNrT1M',
    appId: '1:299785692288:ios:862ef5913703a97d2e3265',
    messagingSenderId: '299785692288',
    projectId: 'chat-app-flutter-fe02d',
    storageBucket: 'chat-app-flutter-fe02d.appspot.com',
    iosClientId: '299785692288-mcpdeg3u9304qgtq412ur6emc0vp9fo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6zyPTrBLivEtrZkpwxeCgW_FlsNrT1M',
    appId: '1:299785692288:ios:63d5b34f32e855ec2e3265',
    messagingSenderId: '299785692288',
    projectId: 'chat-app-flutter-fe02d',
    storageBucket: 'chat-app-flutter-fe02d.appspot.com',
    iosClientId: '299785692288-04muhf067bhp7lgp9h6mm3adfq5i8hrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterChatApp.RunnerTests',
  );
}
